FROM ubuntu:22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 python3-pip mininet openvswitch-switch iproute2 iputils-ping && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app
RUN pip3 install -e .

CMD ["bash", "docker/entrypoints/run_mn.sh"]
