FROM ubuntu:22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 python3-pip curl ca-certificates docker.io iproute2 iputils-ping && \
    rm -rf /var/lib/apt/lists/*

RUN bash -c "$(curl -sL https://get.containerlab.dev)"

WORKDIR /app
COPY . /app
RUN pip3 install -e .

CMD ["bash", "docker/entrypoints/run_clab_exp.sh"]
