
#!/bin/bash
# exp 1
echo "experiment 1"
echo ""

DIR="contrib/romam/NSDI2025/exp1/"
FILE="dgr-packet.delay"

# # OSPF
# PROTCOL="ospf"
# echo "${PROTOCOL}"
# cp "${DIR}code/${PROTCOL}.cc" "scratch/${PROTCOL}-exp1.cc"

# TOPO="2by2"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="3by3"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="4by4"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="5by5"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="6by6"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="7by7"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="8by8"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="9by9"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="10by10"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="abilene"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="att"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="cernet"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="geant"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"

# # DGR
# PROTCOL="dgr"
# echo "${PROTOCOL}"
# cp "${DIR}code/${PROTCOL}.cc" "scratch/${PROTCOL}-exp1.cc"

# TOPO="2by2"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="3by3"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="4by4"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="5by5"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="6by6"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="7by7"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="8by8"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="9by9"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="10by10"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="abilene"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="att"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="cernet"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="geant"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"


# # DDR
# PROTCOL="ddr"
# echo "${PROTOCOL}"
# cp "${DIR}code/${PROTCOL}.cc" "scratch/${PROTCOL}-exp1.cc"

# TOPO="2by2"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="3by3"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="4by4"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="5by5"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="6by6"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="7by7"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="8by8"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="9by9"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="10by10"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="abilene"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="att"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="cernet"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
# TOPO="geant"
# ./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"



# Octopus
PROTCOL="octopus"
echo "${PROTOCOL}"
cp "${DIR}code/${PROTCOL}.cc" "scratch/${PROTCOL}-exp1.cc"

TOPO="2by2"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="3by3"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="4by4"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="5by5"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="6by6"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="7by7"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="8by8"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="9by9"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="10by10"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="abilene"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="att"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="cernet"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
TOPO="geant"
./ns3 run "scratch/${PROTCOL}-exp1.cc --topo=${TOPO}"
